version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGOOB_URI=mongodb+srv://jjjminh123jjj:sc3OhpRKQfTA5EoJ@cluster0.63jzo.mongodb.net/?retryWrites=true&w=majority
      - ACCESS_TOKEN=ACCESS_TOKEN
      - JWT_SECRET=lanlshoinlkakoinjkanaln
      - EMAIL_USER="jjjminh123jjj@gmail.com"
      - EMAIL_PASS='eqpildqkoqpudpvr'
      - CLOUDINARY_CLOUD_NAME=dlkh0eizt
      - CLOUDINARY_API_KEY=955527327797349
      - CLOUDINARY_API_SECRET=a1gKB72kUhOXLZ7hlM8nCeUl-fQ
    depends_on:
      - db
      - redis

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:latest
    ports:
      - "6379:6379"